[package]
name = "bookmark-checker"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "5"
serde_json = "1"
indicatif = "0.17"
rayon = "1"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "rustls-tls"] }
